#!/usr/bin/env bash
# Run a single chaos scenario end-to-end with in-cluster k6:
#   1. reset the ledger collector (drop prior segments)
#   2. apply the k6-script ConfigMap and submit the k6 Job
#   3. start metric port-forwards and snapshot at fault_start
#   4. wait PRE_FAULT_S, mark fault_start
#   5. inject the fault — either a Chaos Mesh CR (scenarios/<ID>-*.yaml)
#      or an action script (scenarios/<ID>-*.sh). The runner picks
#      whichever exists; if both exist, the script wins.
#   6. mark fault_end, snapshot metrics, wait POST_FAULT_S for convergence,
#      snapshot again at scenario_end
#   7. wait for k6 Job to finish, pull ledger, analyze, threshold-check
#
# Traffic is generated by an in-cluster k6 Job (see manifests/k6-job.yaml).
# The collector is reset per run via POST /reset, so the analyzer always
# sees a clean ledger — no time-window scoping needed.
#
# Metric scraping uses separate, short-lived port-forwards for the
# operator and one chaperone pod's /metrics; see lib/metrics-scrape.sh.
#
# Usage: run.sh <SCENARIO_ID>
set -euo pipefail

id=${1:?scenario id required, e.g. C01}
root=$(cd "$(dirname "$0")" && pwd)
env_file=$(ls "$root/scenarios/${id}".env 2>/dev/null || true)
action_script=$(ls "$root/scenarios/${id}"-*.sh 2>/dev/null | head -n1 || true)
cr_file=$(ls "$root/scenarios/${id}"-*.yaml 2>/dev/null | head -n1 || true)

if [[ -z "$env_file" ]]; then
  echo "scenario $id not found (need scenarios/${id}.env)" >&2
  exit 2
fi
if [[ -z "$action_script" && -z "$cr_file" ]]; then
  echo "scenario $id needs either scenarios/${id}-*.sh or scenarios/${id}-*.yaml" >&2
  exit 2
fi

# shellcheck source=/dev/null
source "$env_file"
# shellcheck source=lib/common.sh
source "$root/lib/common.sh"
# shellcheck source=lib/k6-job.sh
source "$root/lib/k6-job.sh"
# shellcheck source=lib/metrics-scrape.sh
source "$root/lib/metrics-scrape.sh"

: "${GATEWAY_URL:=http://${GATEWAY_NAME}.${CHAOS_NS}.svc.cluster.local}"
: "${COLLECTOR_URL:=http://ledger-collector.${CHAOS_NS}.svc.cluster.local:8080}"
: "${DURATION:?set in scenario env}"
: "${PRE_FAULT_S:?set in scenario env}"
: "${POST_FAULT_S:?set in scenario env}"
: "${VUS:=50}"
: "${RPS:=0}"
export GATEWAY_URL COLLECTOR_URL

# Minimum k6 samples the analyzer must see for the run to be considered
# to have actually driven traffic.
: "${MIN_TOTAL:=50}"

for bin in kubectl envsubst jq go; do
  command -v "$bin" >/dev/null 2>&1 || {
    echo "FAIL: $bin not on PATH" >&2
    exit 2
  }
done

# mark.sh runs on the host, so it uses the local port-forward rather
# than the in-cluster service DNS that k6 / echo use.
mark() {
  COLLECTOR_URL="http://127.0.0.1:${collector_port:-9090}" \
    "$root/lib/mark.sh" "$@"
}

outdir=$(mktemp -d)
metrics_dir="$outdir/metrics"
job_name=""
pf_pid=""

cleanup() {
  metrics_scrape_stop
  if [[ -n "$cr_file" ]]; then
    kubectl delete -f "$cr_file" --ignore-not-found >/dev/null 2>&1 || true
  fi
  if [[ -n "$job_name" ]]; then
    k6_job_cleanup "$job_name"
  fi
  if [[ -n "${pf_pid:-}" ]]; then
    kill "$pf_pid" 2>/dev/null || true
    wait "$pf_pid" 2>/dev/null || true
  fi
  rm -rf "$outdir"
}
trap cleanup EXIT

# Short-lived port-forward to the collector for reset + download. This
# is off the traffic hot path — k6 talks to the collector in-cluster.
collector_pod=$(kubectl -n "$CHAOS_NS" get pod -l app=ledger-collector -o name | head -n1)
if [[ -z "$collector_pod" ]]; then
  echo "FAIL: no ledger-collector pod running" >&2
  exit 2
fi
collector_port=$(( 10000 + RANDOM % 20000 ))
kubectl -n "$CHAOS_NS" port-forward "$collector_pod" "${collector_port}:8080" \
  >"$outdir/pf.log" 2>&1 &
pf_pid=$!
for _ in 1 2 3 4 5 6 7 8 9 10; do
  curl -fsS "http://127.0.0.1:${collector_port}/healthz" >/dev/null 2>&1 && break
  sleep 0.5
done
if ! curl -fsS "http://127.0.0.1:${collector_port}/healthz" >/dev/null 2>&1; then
  echo "FAIL: collector port-forward never came up" >&2
  cat "$outdir/pf.log" >&2 || true
  exit 2
fi

curl -fsS -X POST "http://127.0.0.1:${collector_port}/reset" >/dev/null || {
  echo "FAIL: could not reset collector ledger" >&2
  exit 2
}

metrics_ok=1
metrics_scrape_start "$metrics_dir" || metrics_ok=0

k6_apply_script
duration_s=$(duration_to_seconds "$DURATION")
deadline=$(( duration_s + PRE_FAULT_S + POST_FAULT_S + 120 ))

job_name=$(k6_job_start "$id" "$DURATION" "$VUS" "$RPS" "$deadline")
echo "k6 Job started: $job_name (deadline ${deadline}s)"

# Catch ConfigMap / image-pull failures before we inject the fault.
k6_job_await_ready "$job_name" 60 || exit 2

# 3. Warm-up, then inject fault.
sleep "$PRE_FAULT_S"

if (( metrics_ok )); then
  metrics_snapshot fault_start
  date +%s%3N >"$metrics_dir/.fault_start_ts"
fi

if [[ -n "$action_script" ]]; then
  mark "${id}_fault_start" "$(basename "$action_script")"
  bash "$action_script"
  mark "${id}_fault_end" "$(basename "$action_script")"
else
  mark "${id}_fault_start" "$(basename "$cr_file")"
  kubectl apply -f "$cr_file"
  sleep "${WAIT_S:-5}"
  kubectl delete -f "$cr_file" --ignore-not-found
  mark "${id}_fault_end" "$(basename "$cr_file")"
fi

if (( metrics_ok )); then
  metrics_snapshot fault_end
  date +%s%3N >"$metrics_dir/.fault_end_ts"
fi

# 4. Let things converge.
sleep "$POST_FAULT_S"

if (( metrics_ok )); then
  metrics_snapshot scenario_end
fi

# k6 finishes on its own after DURATION; deadline already has slack baked
# in, so no extra margin here.
if ! k6_job_wait "$job_name" "$deadline"; then
  echo "FAIL: k6 Job $job_name did not complete cleanly" >&2
  exit 1
fi

mkdir -p dist
k6_job_logs "$job_name" "dist/${id}-k6.log"

curl -fsS "http://127.0.0.1:${collector_port}/download" -o "$outdir/ledger.ndjson"

go run "$root/../load/analyze" -f "$outdir/ledger.ndjson" -json >"$outdir/report.json"
cp "$outdir/report.json" "dist/${id}-report.json"
cp "$outdir/ledger.ndjson" "dist/${id}-ledger.ndjson"

# 7. Check thresholds.
total=$(jq -r '.total // 0' "$outdir/report.json")
drop_ratio=$(jq -r '.drop_ratio // 0' "$outdir/report.json")
misroutes=$(jq -r '.misroutes // 0' "$outdir/report.json")
non_2xx=$(jq -r '.non_2xx // 0' "$outdir/report.json")
converge_ms=$(jq -r --arg id "$id" '.convergence[$id + "_fault_end"] // 0' "$outdir/report.json")

fail=0
if (( total < MIN_TOTAL )); then
  echo "FAIL: total=$total < MIN_TOTAL=$MIN_TOTAL — k6 did not drive traffic"
  echo "  k6 log saved to dist/${id}-k6.log"
  fail=1
fi
if awk -v a="$drop_ratio" -v b="${MAX_DROP_RATIO:-1}" 'BEGIN{exit !(a+0 > b+0)}'; then
  echo "FAIL: drop_ratio=$drop_ratio > ${MAX_DROP_RATIO:-1}"; fail=1
fi
if (( misroutes > ${MAX_MISROUTES:-0} )); then
  echo "FAIL: misroutes=$misroutes > ${MAX_MISROUTES:-0}"; fail=1
fi
if (( converge_ms > ${MAX_CONVERGE_MS:-0} )); then
  echo "FAIL: converge_ms=$converge_ms > ${MAX_CONVERGE_MS:-0}"; fail=1
fi

metrics_summary=
if (( metrics_ok )); then
  metrics_summary=$("$root/lib/metrics-summary.sh" "$metrics_dir" 2>/dev/null || echo "")
fi

# Metrics-based thresholds are opt-in. An unset env var skips the check.
check_metric() {
  local label=$1 path=$2 limit=$3
  [[ -z "$limit" ]] && return 0
  [[ -z "$metrics_summary" ]] && return 0
  local v
  v=$(echo "$metrics_summary" | jq -r "$path // 0")
  if awk -v a="$v" -v b="$limit" 'BEGIN{exit !(a+0 > b+0)}'; then
    echo "FAIL: $label=$v > $limit"; fail=1
  fi
}

check_metric "operator.goroutines_delta"     ".operator.goroutines.delta"     "${MAX_OPERATOR_GOROUTINE_DELTA:-}"
check_metric "operator.workqueue_depth_end"  ".operator.workqueue_depth_end"  "${MAX_OPERATOR_WORKQUEUE_DEPTH_END:-}"
check_metric "operator.reconcile_rate_hz"    ".operator.reconcile_rate_hz"    "${MAX_OPERATOR_RECONCILE_RATE_HZ:-}"
check_metric "operator.reconcile_avg_ms"     ".operator.reconcile_avg_ms"     "${MAX_OPERATOR_RECONCILE_AVG_MS:-}"
check_metric "operator.reconcile_errors"     ".operator.reconcile_errors"     "${MAX_OPERATOR_RECONCILE_ERRORS:-}"
check_metric "operator.open_fds_delta"       ".operator.open_fds.delta"       "${MAX_OPERATOR_FDS_DELTA:-}"
check_metric "chaperone.goroutines_delta"    ".chaperone.goroutines.delta"    "${MAX_CHAPERONE_GOROUTINE_DELTA:-}"
check_metric "chaperone.ghost_reload_errors" ".chaperone.ghost_reload_errors" "${MAX_CHAPERONE_RELOAD_ERRORS:-}"

if [[ -n "$metrics_summary" ]]; then
  echo "$metrics_summary" >"dist/${id}-metrics.json"
  mkdir -p "dist/${id}-metrics"
  cp "$metrics_dir"/*.prom "dist/${id}-metrics/" 2>/dev/null || true
fi

summary="total=$total drop_ratio=$drop_ratio non_2xx=$non_2xx misroutes=$misroutes converge_ms=$converge_ms"
if (( fail )); then
  echo "scenario $id FAILED ($summary) report: dist/${id}-report.json"
  exit 1
fi
echo "scenario $id PASSED ($summary)"
